version: '3.9'
services:
  server:
    build: server
    ports:
      - "8080:8080"
  client:
    build: client
    environment:
      - SERVER=server
    links:
      - server
    depends_on:
      - server
